#!/bin/sh
 
### BEGIN INIT INFO
# Provides:          iyri (Wraith Sensor Daemon)
# Short-Description: Initiates Iyri, an Wraith sensor
# Author: Dale Patterson <wraith.wireless@yandex.com>
### END INIT INFO

# Change the next 3 lines to suit where script is installed and what its called
PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/home/<user>/workspace/projects/Python/wraith/iyri/iyri.py
DAEMON_NAME=iyrid

#DAEMON_USER=root

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

# source init functions
. /lib/lsb/init-functions

do_start() {
    log_daemon_msg "Starting $DAEMON_NAME"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pid --startas $DAEMON
    # sleep, giving time for iyri to succeed/fail
    sleep 3
    log_end_msg $?
}

# manually remove the pidfile as ubuntu does not recognize the flag --remove-pidfile
do_stop() {
    log_daemon_msg "Stopping $DAEMON_NAME"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
    rm $PIDFILE
}

case "$1" in
    start)
      do_start
     ;;
    stop)
      do_stop
     ;;
    restart)
      do_stop
      do_start
     ;;
    status)
     status_of_proc "$DAEMON_NAME" && exit 0 || exit $?
     ;;
    *)
      echo "Usage: /etc/init.d/iyrid {start|stop|restart|status}"
      exit 1
     ;;
esac