#!/bin/sh
 
### BEGIN INIT INFO
# Provides:          iyri (Wraith Sensor Daemon)
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Initiates Iyri, an Wraith sensor
### END INIT INFO

# Author: Dale Patterson <wraith.wireless@yandex.com>

# Change the next 3 lines to suit where script is installed and what its called
PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/home/<user>/workspace/projects/Python/wraith/iyri/iyri.py
DAEMON_NAME=iyrid

# uncomment below, replace <user> with login to run as user
#DAEMON_USER=<user>

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

# source init functions
. /lib/lsb/init-functions

do_start() {
    # if running at user level, uncomment the below two lines & the three lines
    # prior to log_end_msg $? This will set the raw socket before initiating the
    # sensor allowing iyri to bind it - have to sleep to allow sensor to initiate
    # fully before remove raw capture capability
    #log_daemon_msg "Setting capability cap_net_raw"
    #setcap cap_net_raw=+ep /usr/bin/python2.7
    log_daemon_msg "Starting $DAEMON_NAME"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pid --startas $DAEMON
    #sleep 2
    #log_daemon_msg "Removing capability cap_net_raw"
    #setcap cap_net_raw=-ep /usr/bin/python2.7
    log_end_msg $?
}

# manually remove the pidfile as ubuntu does not recognize the flag --remove-pidfile
do_stop() {
    log_daemon_msg "Stopping $DAEMON_NAME"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
    rm $PIDFILE
}

case "$1" in
    start)
      do_start
     ;;
    stop)
      do_stop
     ;;
    restart)
      do_stop
      do_start
     ;;
    status)
     status_of_proc "$DAEMON_NAME" && exit 0 || exit $?
     ;;
    *)
      echo "Usage: /etc/init.d/iyrid {start|stop|restart|status}"
      exit 1
     ;;
esac
